task_manager/labels/urls.py
from django.urls import path
from task_manager.labels import views


urlpatterns = [
    path("", views.IndexView.as_view(), name="labels_index"),
    path("create/", views.LabelCreateView.as_view(), name="labels_create"),
    path("<int:pk>/update/", views.LabelUpdateView.as_view(), name="labels_update"),
    path("<int:pk>/delete/", views.LabelDeleteView.as_view(), name="labels_delete"),
]

task_manager/tasks/urls.py
from django.urls import path
from task_manager.tasks import views


urlpatterns = [
    path("", views.IndexView.as_view(), name="tasks_index"),
    path("create/", views.TaskCreateView.as_view(), name="tasks_create"),
    path("<int:pk>/update/", views.TaskUpdateView.as_view(), name="tasks_update"),
    path("<int:pk>/delete/", views.TaskDeleteView.as_view(), name="tasks_delete"),
    path("<int:pk>/", views.TaskDetailView.as_view(), name="tasks_detail"),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from task_manager import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('login/', views.UsersLoginView.as_view(), name="login"),
    path("logout/", views.UsersLogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

task_manager/users/urls.py
from django.urls import path
from task_manager.users import views


urlpatterns = [
    path('', views.IndexView.as_view(), name="users_index"),
    path('create/', views.UserFormCreateView.as_view(), name="users_create"),
    path("<int:pk>/update/", views.UserUpdateView.as_view(), name="users_update"),
    path("<int:pk>/delete/", views.UserDeleteView.as_view(), name="users_delete"),
]

task_manager/labels/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Label(models.Model):
    name = models.CharField(_("name"), max_length=50)
    created_at = models.DateTimeField(_("created at"), auto_now=True)

    def __str__(self):
        return self.name

task_manager/statuses/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Status(models.Model):
    name = models.CharField(_("name"), max_length=50)
    created_at = models.DateTimeField(_("created at"), auto_now=True)

    def __str__(self):
        return self.name

task_manager/tasks/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _
from task_manager.labels.models import Label
from task_manager.statuses.models import Status


class Task(models.Model):
    name = models.CharField(_("name"), max_length=50)
    description = models.TextField(_("description"))
    status = models.ForeignKey(
        Status,
        verbose_name=_("status"),
        on_delete=models.PROTECT,
        null=True,
    )
    creator = models.ForeignKey(
        get_user_model(),
        verbose_name=_("creator"),
        on_delete=models.PROTECT,
        related_name="creator",
    )
    executor = models.ForeignKey(
        get_user_model(),
        verbose_name=_("executor"),
        on_delete=models.PROTECT,
        related_name="executor",
    )
    created_at = models.DateTimeField(_("created at"), auto_now=True)
    labels = models.ManyToManyField(
        Label,
        verbose_name=_("labels"),
        blank=True,
        related_name="labels",
        through="TaskLabel",
    )

    def __str__(self):
        return self.name


class TaskLabel(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    label = models.ForeignKey(Label, on_delete=models.RESTRICT)

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class User(AbstractUser):
    def __str__(self):
        return self.get_full_name()

    def get_absolute_url(self):
        return reverse("login")

task_manager/labels/forms.py
from django.forms import ModelForm
from .models import Label


class LabelForm(ModelForm):

    class Meta:
        model = Label
        fields = ["name"]

task_manager/statuses/forms.py
from django.forms import ModelForm
from .models import Status


class StatusForm(ModelForm):

    class Meta:
        model = Status
        fields = ["name"]

task_manager/tasks/forms.py
from django.forms import ModelForm
from .models import Task


class TaskForm(ModelForm):

    class Meta:
        model = Task
        fields = ["name", "description", "status", "executor", "labels"]

task_manager/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class UserForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ("first_name", "last_name")

task_manager/labels/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import RestrictedError
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from .forms import LabelForm
from .models import Label


class IndexView(LoginRequiredMixin, ListView):
    template_name = "labels/index.html"
    model = Label


class LabelCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Label
    form_class = LabelForm
    template_name = "labels/create.html"
    success_url = reverse_lazy("labels_index")
    success_message = _("Label successfully created")


class LabelUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Label
    form_class = LabelForm
    template_name = "labels/update.html"
    success_url = reverse_lazy("labels_index")
    success_message = _("Label successfully updated")


class LabelDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Label
    success_url = reverse_lazy("labels_index")
    template_name = "labels/delete.html"

    def form_valid(self, form):
        success_url = self.get_success_url()
        try:
            self.object.delete()
        except RestrictedError:
            messages.error(
                self.request,
                _("Label is used by task"),
            )
        else:
            messages.success(
                self.request,
                _("Label successfully deleted"),
            )
        return HttpResponseRedirect(success_url)

task_manager/statuses/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import ProtectedError
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from .forms import StatusForm
from .models import Status


class IndexView(LoginRequiredMixin, ListView):
    template_name = "statuses/index.html"
    model = Status


class StatusFormCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Status
    form_class = StatusForm
    template_name = "statuses/create.html"
    success_url = reverse_lazy("statuses_index")
    success_message = _("Status successfully created")


class StatusUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Status
    form_class = StatusForm
    template_name = "statuses/update.html"
    success_url = reverse_lazy("statuses_index")
    success_message = _("Status successfully updated")


class StatusDeleteView(LoginRequiredMixin, DeleteView):
    model = Status
    success_url = reverse_lazy("statuses_index")
    template_name = "statuses/delete.html"

    def form_valid(self, form):
        success_url = self.get_success_url()
        try:
            self.object.delete()
        except ProtectedError:
            messages.error(
                self.request,
                _("Status is used by task"),
            )
        else:
            messages.success(
                self.request,
                _("Status successfully deleted"),
            )
        return HttpResponseRedirect(success_url)

task_manager/tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django_filters.views import FilterView
from .filters import TaskFilter
from .forms import TaskForm
from .mixins import CheckTaskCreator
from .models import Task


class IndexView(LoginRequiredMixin, FilterView):
    template_name = "tasks/index.html"
    model = Task
    filterset_class = TaskFilter


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = "tasks/detail.html"


class TaskCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = "tasks/create.html"
    success_url = reverse_lazy("tasks_index")
    success_message = _("Task successfully created")

    def form_valid(self, form):
        form.instance.creator = self.request.user

        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "tasks/update.html"
    success_url = reverse_lazy("tasks_index")
    success_message = _("Task successfully updated")


class TaskDeleteView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    CheckTaskCreator,
    DeleteView,
):
    model = Task
    success_url = reverse_lazy("tasks_index")
    success_message = _("Task successfully deleted")
    template_name = "tasks/delete.html"

task_manager/users/views.py
from django.utils.translation import gettext as _
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.db.models import ProtectedError
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from .models import User
from .forms import UserForm
from .mixins import UserHasPermissionMixin


# Create your views here.
class IndexView(ListView):
    template_name = "users/index.html"
    model = User


class UserFormCreateView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserForm
    template_name = 'users/create.html'
    succes_url = reverse_lazy("login")
    success_message = _("User successfully registred")


class UserUpdateView(UserHasPermissionMixin, SuccessMessageMixin, UpdateView):
    model = User
    form_class = UserForm
    template_name = "users/update.html"
    success_url = reverse_lazy("users_index")
    success_message = _("User successfully updated")


class UserDeleteView(UserHasPermissionMixin, DeleteView):
    model = User
    success_url = reverse_lazy("users_index")
    template_name = "users/delete.html"

    def form_valid(self, form):
        success_url = self.get_success_url()
        try:
            self.object.delete()
        except ProtectedError:
            messages.error(
                self.request,
                _("Cannot delete a user because he is being used"),
            )
        else:
            messages.success(
                self.request,
                _("User successfully deleted"),
            )
        return HttpResponseRedirect(success_url)

task_manager/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls.base import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic.base import TemplateView


class IndexView(TemplateView):

    template_name = "index.html"


class UsersLoginView(SuccessMessageMixin, LoginView):
    success_message = _("You are logged in")
    template_name = "login.html"

    def get_success_url(self):
        return reverse_lazy("index")


class UsersLogoutView(LogoutView):
    next_page = reverse_lazy("index")

    def dispatch(self, request, *args, **kwargs):
        messages.info(request, _("You are logged out"))
        return super().dispatch(request, *args, **kwargs)

task_manager/templates/users/create.html
{% extends "index.html" %} 
{% load i18n %}
{% load bootstrap4 %}
{% block content %}
<h1 class="display-4 fw-bold mt-4">{% translate "Registration" %}</h1>
<div class="row justify-content-center">
  <div class="col-12 col-md-8">
      <div class="card shadow-sm">
          <div class="card-body row p-5">
              <div
              class="col-12 col-md-8 d-flex align-items-center justify-content-center"
              >
            </div>
            <div class="col-12 col-md-8 mt-3 mt-mb-0">
                <form action="{% url 'users_create' %}" method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
            <button class="btn btn-primary">{% translate "Registers" %}</button>
                </form>
    </div>
</div>
</div>
</div>
</div>
{% endblock %}

task_manager/templates/users/delete.html
{% extends "index.html" %} 
{% load i18n %}
{% block content %}
<h1 class="display-4 fw-bold mt-4">{% translate "Are you really want to delete user?" %}</h1>
<div class="row justify-content-center">
  <div class="col-12 col-md-8">
      <div class="card shadow-sm">
          <div class="card-body row p-5">
              <div
              class="col-12 col-md-8 d-flex align-items-center justify-content-center"
              >
            </div>
            <div class="col-12 col-md-8 mt-3 mt-mb-0">
                <form action="{% url 'users_delete' pk=user.id %}" method="post">
                    {% csrf_token %}
            <button class="btn btn-primary">{% translate "Yes, delete" %}</button>
                </form>
    </div>
</div>
</div>
</div>
</div>
{% endblock %}

task_manager/templates/users/index.html
{% extends "index.html" %}
{% load i18n %}
{% block content %}
    <h1 class="display-4 fw-bold mt-4">{% translate "Users" %}</h1>

    <div class="table-responsive">
        <table class="table table-borderless table-striped mt-5 bg-white">
        <thead>
          <tr>
            <th>ID</th>
            <th>{% translate "Username" %}</th>
            <th>{% translate "Full Name" %}</th>
            <th>{% translate "Created at" %}</th>
            <th>{% translate "Actions" %}</th>
          </tr>
        </thead>
        
        <tbody>
        {% for user in user_list %}
            <tr>
            <th scope="row">{{ user.id }}</th>
            <td>{{ user.username }}</td>
            <td>{{ user.get_full_name }}</td>
            <td>{{ user.date_joined }}</td>
            <td>
              <a href="{% url 'users_update' pk=user.id %}">{% translate "Update" %}</a>
              <a href="{% url 'users_delete' pk=user.id %}">{% translate "Delete" %}</a>
            </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

task_manager/templates/users/update.html
{% extends "index.html" %} 
{% load i18n %}
{% load bootstrap4 %}

{% block content %}
<h1 class="display-4 fw-bold mt-4">{% translate "Update user" %}</h1>
<div class="row justify-content-center">
  <div class="col-12 col-md-8">
      <div class="card shadow-sm">
          <div class="card-body row p-5">
              <div
              class="col-12 col-md-8 d-flex align-items-center justify-content-center"
              >
            </div>
            <div class="col-12 col-md-8 mt-3 mt-mb-0">
                <form action="{% url 'users_update' pk=user.id %}" method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                <button class="btn btn-primary">{% translate "Update" %}</button>
                </form>
    </div>
</div>
</div>
</div>
</div>
{% endblock %}